name: train-model
on: [push]
jobs:
  run:
    runs-on: [self-hosted, Linux,X64]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " Hi, I am from self-hosted GPU!" > report.md

          # Write your CML report
          cml-send-comment report.md
